// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    /// <summary>
    /// Represents a Todo item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TodoItemModel : IParsable
    {
        /// <summary>Gets or sets the date and time the item was completed.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>Gets or sets the date and time the item was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Gets or sets the ID of the Todo item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets the date and time the Todo item was last updated.</summary>
        public DateTimeOffset? LastUpdated { get; set; }
        /// <summary>Gets or sets the optional priority of the Todo item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority? Priority { get; set; }
#nullable restore
#else
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority Priority { get; set; }
#endif
        /// <summary>Gets or sets the text of the Todo item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastUpdated", n => { LastUpdated = n.GetDateTimeOffsetValue(); } },
                { "priority", n => { Priority = n.GetObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority>(global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastUpdated", LastUpdated);
            writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority>("priority", Priority);
            writer.WriteStringValue("text", Text);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel_priorityMember1"/>, <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoPriority"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TodoItemModel_priority : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel_priorityMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel_priorityMember1? TodoItemModelPriorityMember1 { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel_priorityMember1 TodoItemModelPriorityMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoPriority"/></summary>
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoPriority? TodoPriority { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel.TodoItemModel_priority();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.TodoItemModelPriorityMember1 = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel_priorityMember1();
                }
                else if(parseNode.GetEnumValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoPriority>() is global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoPriority todoPriorityValue)
                {
                    result.TodoPriority = todoPriorityValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TodoItemModelPriorityMember1 != null)
                {
                    return TodoItemModelPriorityMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(TodoItemModelPriorityMember1 != null)
                {
                    writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoItemModel_priorityMember1>(null, TodoItemModelPriorityMember1);
                }
                else if(TodoPriority != null)
                {
                    writer.WriteEnumValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoPriority>(null, TodoPriority);
                }
            }
        }
    }
}
#pragma warning restore CS0618
