// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \animals\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnimalsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnimalsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/animals/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnimalsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/animals/{id}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse?> GetAsAnimalsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse> GetAsAnimalsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse>(requestInfo, global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsAnimalsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse>(requestInfo, global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat"/>, <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AnimalsGetResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat? Cat { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat Cat { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog? Dog { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog Dog { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsGetResponse();
                result.Cat = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat();
                result.Dog = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Cat != null || Dog != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(Cat, Dog);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat>(null, Cat, Dog);
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AnimalsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat"/>, <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AnimalsResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat? Cat { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat Cat { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog? Dog { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog Dog { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.Item.AnimalsItemRequestBuilder.AnimalsResponse();
                result.Cat = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat();
                result.Dog = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Dog();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Cat != null || Dog != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(Cat, Dog);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Cat>(null, Cat, Dog);
            }
        }
    }
}
#pragma warning restore CS0618
