// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Orders;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTenantItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The orders property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.ProductsRequestBuilder Products
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.WithTenantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.WithTenantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
