// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse
{
    /// <summary>
    /// Builds and executes requests for operations under \TypeWithTryParse
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TypeWithTryParseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.Item.WithTryParseItemRequestBuilder"/></returns>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.Item.WithTryParseItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tryParse", position);
                return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.Item.WithTryParseItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.TypeWithTryParseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TypeWithTryParseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TypeWithTryParse", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.TypeWithTryParseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TypeWithTryParseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TypeWithTryParse", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
