// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DateTimeKindObject
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Unspecified")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "Utc")]
        #pragma warning disable CS1591
        Utc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Local")]
        #pragma warning disable CS1591
        Local,
        #pragma warning restore CS1591
    }
}
