// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.Validate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes
{
    /// <summary>
    /// Builds and executes requests for operations under \zip-codes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ZipCodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The validate property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.Validate.ValidateRequestBuilder Validate
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.Validate.ValidateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.ZipCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ZipCodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zip-codes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.ZipCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ZipCodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zip-codes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
