// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TodoApp.KiotaClient.Models
{
    /// <summary>
    /// Represents the model for updating the priority of a Todo item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateTodoItemPriorityModel : IParsable
    {
        /// <summary>Gets or sets the new priority of the Todo item.</summary>
        public global::TodoApp.KiotaClient.Models.TodoPriority? Priority { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TodoApp.KiotaClient.Models.UpdateTodoItemPriorityModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TodoApp.KiotaClient.Models.UpdateTodoItemPriorityModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TodoApp.KiotaClient.Models.UpdateTodoItemPriorityModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "priority", n => { Priority = n.GetEnumValue<global::TodoApp.KiotaClient.Models.TodoPriority>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::TodoApp.KiotaClient.Models.TodoPriority>("priority", Priority);
        }
    }
}
#pragma warning restore CS0618
