// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemTextJsonDefaultDiscriminatorAnimal : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The animalType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnimalType { get; set; }
#nullable restore
#else
        public string AnimalType { get; set; }
#endif
        /// <summary>The Type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.SystemTextJsonDefaultDiscriminatorAnimal"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.SystemTextJsonDefaultDiscriminatorAnimal CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("$type")?.GetStringValue();
            return mappingValue switch
            {
                "Cat" => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.SystemTextJsonDefaultDiscriminatorCat(),
                "Dog" => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.SystemTextJsonDefaultDiscriminatorDog(),
                _ => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.SystemTextJsonDefaultDiscriminatorAnimal(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "animalType", n => { AnimalType = n.GetStringValue(); } },
                { "$type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("animalType", AnimalType);
            writer.WriteStringValue("$type", Type);
        }
    }
}
#pragma warning restore CS0618
