// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SecondLevel;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SystemTextJsonAnimals;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SystemTextJsonDefaultDiscriminatorAnimals;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KiotaOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The Animals property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.AnimalsRequestBuilder Animals
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Animals.AnimalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SecondLevel property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SecondLevel.SecondLevelRequestBuilder SecondLevel
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SecondLevel.SecondLevelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SystemTextJsonAnimals property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SystemTextJsonAnimals.SystemTextJsonAnimalsRequestBuilder SystemTextJsonAnimals
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SystemTextJsonAnimals.SystemTextJsonAnimalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SystemTextJsonDefaultDiscriminatorAnimals property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SystemTextJsonDefaultDiscriminatorAnimals.SystemTextJsonDefaultDiscriminatorAnimalsRequestBuilder SystemTextJsonDefaultDiscriminatorAnimals
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.SystemTextJsonDefaultDiscriminatorAnimals.SystemTextJsonDefaultDiscriminatorAnimalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.KiotaOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KiotaOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
