// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Addresses;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Carts;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Country;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Dragons;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Files;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Issue3013;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Kittens;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Orders;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Products;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Promotions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Registrations;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.RegistrationsWithEnumParameter;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.RegistrationsWithIgnoreProperties;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Shapes;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Stores;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Unicorns;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KiotaOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The addresses property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Addresses.AddressesRequestBuilder Addresses
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Addresses.AddressesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The carts property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Carts.CartsRequestBuilder Carts
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Carts.CartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The country property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Country.CountryRequestBuilder Country
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Country.CountryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dragons property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Dragons.DragonsRequestBuilder Dragons
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Dragons.DragonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Files.FilesRequestBuilder Files
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Issue3013 property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Issue3013.Issue3013RequestBuilder Issue3013
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Issue3013.Issue3013RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The kittens property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Kittens.KittensRequestBuilder Kittens
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Kittens.KittensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Products.ProductsRequestBuilder Products
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The promotions property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Promotions.PromotionsRequestBuilder Promotions
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Promotions.PromotionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The registrations property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Registrations.RegistrationsRequestBuilder Registrations
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Registrations.RegistrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The registrationsWithEnumParameter property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.RegistrationsWithEnumParameter.RegistrationsWithEnumParameterRequestBuilder RegistrationsWithEnumParameter
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.RegistrationsWithEnumParameter.RegistrationsWithEnumParameterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The registrationsWithIgnoreProperties property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.RegistrationsWithIgnoreProperties.RegistrationsWithIgnorePropertiesRequestBuilder RegistrationsWithIgnoreProperties
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.RegistrationsWithIgnoreProperties.RegistrationsWithIgnorePropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shapes property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Shapes.ShapesRequestBuilder Shapes
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Shapes.ShapesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stores property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Stores.StoresRequestBuilder Stores
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Stores.StoresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unicorns property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Unicorns.UnicornsRequestBuilder Unicorns
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Unicorns.UnicornsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zipCodes property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.ZipCodesRequestBuilder ZipCodes
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.ZipCodes.ZipCodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.KiotaOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KiotaOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
