// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.Delete.List;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.Delete
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}\products\Delete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The List property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.Delete.List.ListRequestBuilder List
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.Delete.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/products/Delete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Item.Products.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/products/Delete", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
