// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType
{
    /// <summary>
    /// Builds and executes requests for operations under \XmlComments\CarWithProducesDefaultResponseType
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CarWithProducesDefaultResponseTypeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarWithProducesDefaultResponseTypeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/XmlComments/CarWithProducesDefaultResponseType?id={id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarWithProducesDefaultResponseTypeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/XmlComments/CarWithProducesDefaultResponseType?id={id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a specific product With ProducesDefaultResponseType attribute
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product?> GetAsync(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder.CarWithProducesDefaultResponseTypeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product> GetAsync(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder.CarWithProducesDefaultResponseTypeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product>(requestInfo, global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Product.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a specific product With ProducesDefaultResponseType attribute
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder.CarWithProducesDefaultResponseTypeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder.CarWithProducesDefaultResponseTypeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a specific product With ProducesDefaultResponseType attribute
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CarWithProducesDefaultResponseTypeRequestBuilderGetQueryParameters 
        {
            [QueryParameter("id")]
            public int? Id { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CarWithProducesDefaultResponseTypeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder.CarWithProducesDefaultResponseTypeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
