// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Parent : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The category property</summary>
        public int? Category { get; set; }
        /// <summary>The child property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child? Child { get; set; }
#nullable restore
#else
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child Child { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetIntValue(); } },
                { "child", n => { Child = n.GetObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child>(global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("category", Category);
            writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child>("child", Child);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Child"/>, <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent_childMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Parent_child : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Child"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Child? Child { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Child Child { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent_childMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent_childMember1? ParentChildMember1 { get; set; }
#nullable restore
#else
            public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent_childMember1 ParentChildMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent.Parent_child();
                if("Child".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Child = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Child();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParentChildMember1 = new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent_childMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Child != null)
                {
                    return Child.GetFieldDeserializers();
                }
                else if(ParentChildMember1 != null)
                {
                    return ParentChildMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Child != null)
                {
                    writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Child>(null, Child);
                }
                else if(ParentChildMember1 != null)
                {
                    writer.WriteObjectValue<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.Parent_childMember1>(null, ParentChildMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
