// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Annotations;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KiotaOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The annotations property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Annotations.AnnotationsRequestBuilder Annotations
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Annotations.AnnotationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TypeWithTryParse property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.TypeWithTryParseRequestBuilder TypeWithTryParse
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.TypeWithTryParse.TypeWithTryParseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The WithOpenApi property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.WithOpenApiRequestBuilder WithOpenApi
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.WithOpenApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The XmlComments property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.XmlCommentsRequestBuilder XmlComments
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.XmlCommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.KiotaOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KiotaOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
