// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreditCard : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cardNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardNumber { get; set; }
#nullable restore
#else
        public string CardNumber { get; set; }
#endif
        /// <summary>The expMonth property</summary>
        public int? ExpMonth { get; set; }
        /// <summary>The expYear property</summary>
        public int? ExpYear { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.CreditCard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.CreditCard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.CreditCard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cardNumber", n => { CardNumber = n.GetStringValue(); } },
                { "expMonth", n => { ExpMonth = n.GetIntValue(); } },
                { "expYear", n => { ExpYear = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cardNumber", CardNumber);
            writer.WriteIntValue("expMonth", ExpMonth);
            writer.WriteIntValue("expYear", ExpYear);
        }
    }
}
#pragma warning restore CS0618
