// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromBody;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFile;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileAndEnum;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileAndString;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileCollection;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromObjectAndString;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.MultipleForms;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.Weatherforecast;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi
{
    /// <summary>
    /// Builds and executes requests for operations under \WithOpenApi
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOpenApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The IFromBody property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromBody.IFromBodyRequestBuilder IFromBody
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromBody.IFromBodyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The IFromFile property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFile.IFromFileRequestBuilder IFromFile
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFile.IFromFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The IFromFileAndEnum property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileAndEnum.IFromFileAndEnumRequestBuilder IFromFileAndEnum
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileAndEnum.IFromFileAndEnumRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The IFromFileAndString property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileAndString.IFromFileAndStringRequestBuilder IFromFileAndString
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileAndString.IFromFileAndStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The IFromFileCollection property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileCollection.IFromFileCollectionRequestBuilder IFromFileCollection
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromFileCollection.IFromFileCollectionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The IFromObjectAndString property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromObjectAndString.IFromObjectAndStringRequestBuilder IFromObjectAndString
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.IFromObjectAndString.IFromObjectAndStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multipleForms property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.MultipleForms.MultipleFormsRequestBuilder MultipleForms
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.MultipleForms.MultipleFormsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The weatherforecast property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.Weatherforecast.WeatherforecastRequestBuilder Weatherforecast
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.Weatherforecast.WeatherforecastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.WithOpenApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOpenApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/WithOpenApi", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.WithOpenApi.WithOpenApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOpenApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/WithOpenApi", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
