// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TestStruct : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The a property</summary>
        public int? A { get; set; }
        /// <summary>The b property</summary>
        public int? B { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TestStruct"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TestStruct CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TestStruct();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "a", n => { A = n.GetIntValue(); } },
                { "b", n => { B = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("a", A);
            writer.WriteIntValue("b", B);
        }
    }
}
#pragma warning restore CS0618
