// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models
{
    /// <summary>The priority levels for a Todo item.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TodoPriority
    {
        [EnumMember(Value = "Normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
        [EnumMember(Value = "Low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "High")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
    }
}
