// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find
{
    /// <summary>
    /// Builds and executes requests for operations under \api\items\find
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FindRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/items/find?IsCompleted={IsCompleted}&Text={Text}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/items/find?IsCompleted={IsCompleted}&Text={Text}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoListViewModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoListViewModel?> GetAsync(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder.FindRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoListViewModel> GetAsync(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder.FindRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoListViewModel>(requestInfo, global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Models.TodoListViewModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder.FindRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder.FindRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class FindRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            /// <summary>Gets or sets a value indicating whether to search completed Todo items.</summary>
            public bool? IsCompleted { get; set; }
            /// <summary>Gets or sets the text of the filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Text { get; set; }
#nullable restore
#else
            public string Text { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FindRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Api.Items.Find.FindRequestBuilder.FindRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
