// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Authorize;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments
{
    /// <summary>
    /// Builds and executes requests for operations under \payments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.payments.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Item.WithPaymentItemRequestBuilder"/></returns>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Item.WithPaymentItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("paymentId", position);
                return new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.Item.WithPaymentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.PaymentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaymentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/payments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.Payments.PaymentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaymentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/payments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
