// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using TodoApp.KiotaClient.Models;
namespace TodoApp.KiotaClient.Api.Items.GetAfter
{
    /// <summary>
    /// Builds and executes requests for operations under \api\items\getAfter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAfterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetAfterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/items/getAfter?value={value}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetAfterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/items/getAfter?value={value}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::TodoApp.KiotaClient.Models.TodoListViewModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::TodoApp.KiotaClient.Models.TodoListViewModel?> GetAsync(Action<RequestConfiguration<global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder.GetAfterRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::TodoApp.KiotaClient.Models.TodoListViewModel> GetAsync(Action<RequestConfiguration<global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder.GetAfterRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::TodoApp.KiotaClient.Models.TodoListViewModel>(requestInfo, global::TodoApp.KiotaClient.Models.TodoListViewModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder.GetAfterRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder.GetAfterRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder WithUrl(string rawUrl)
        {
            return new global::TodoApp.KiotaClient.Api.Items.GetAfter.GetAfterRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class GetAfterRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("value")]
            public DateTimeOffset? Value { get; set; }
        }
    }
}
#pragma warning restore CS0618
