// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.Car;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProduces;
using Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments
{
    /// <summary>
    /// Builds and executes requests for operations under \XmlComments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class XmlCommentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Car property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.Car.CarRequestBuilder Car
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.Car.CarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarWithProduces property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProduces.CarWithProducesRequestBuilder CarWithProduces
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProduces.CarWithProducesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarWithProducesDefaultResponseType property</summary>
        public global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder CarWithProducesDefaultResponseType
        {
            get => new global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.CarWithProducesDefaultResponseType.CarWithProducesDefaultResponseTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.XmlCommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public XmlCommentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/XmlComments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Swashbuckle.AspNetCore.IntegrationTests.KiotaTests.XmlComments.XmlCommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public XmlCommentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/XmlComments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
